# Site settings
title: Desultisoft's Portfolio
description: Check out my projects

# User settings
username: Michael Davis
user_title: Software Developer
email: desultisoft@gmail.com
twitter_username: mides
github_username:  desultisoft

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
